import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ReactPlayer from 'react-player';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SlimAtlanta by ReGenesisDoc LLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className='font20 bold'>The UltraSlim device which is FDA-cleared for immediate fat reduction</h2>
        {/* @ts-ignore */}
        <iframe className='yt-video' width="660" height="360" src="https://www.youtube.com/embed/Aeug85Sr9bc?controls=0&rel=0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>
        <div className='font20'> 
          Please Fill out the Form below to get our PreLaunch Discount in Atlanta and Tucker
        </div>
       
        <p> 
          Hear from the founder
        </p>
        {/* @ts-ignore */}
        <iframe className='yt-video' width="660" height="360" src="https://www.youtube.com/embed/XkM-BY5w69c?controls=0&rel=0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>
        <div className='font20'> 
          Please Fill out the Form below to get our PreLaunch Discount in Atlanta and Tucker
        </div>
        



      {/* @ts-ignore */}
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSd-gPXIqobl3a_UJ5Bs7dr426RK1NUUXp9g5WAgMIC8TI3gew/viewform?embedded=true" className="googleform" width="640" height="760" frameBorder="0" marginHeight="0" marginWidth="0">Loading…</iframe>
      </main>

    </>
  )
}

export default Home 
