import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Form.module.css'
import axios from 'axios';
import { useForm, SubmitHandler } from 'react-hook-form';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();

  const { register, handleSubmit, watch,formState: { errors }} = useForm();


  const onSubmit: SubmitHandler<any> = (data: any) => {
    axios
      .post('/api/emailleadinfo', data)
      .then((_res) => {
        alert('Your Message has been emailed to admin');
        router.push('/clientdetails')
      })
      .catch((err) => console.log(err));
      
      console.log(data);
  };

  return (
    <>
      <Head>
        <title>SlimAtlanta by ReGenesisDoc LLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className='font20 bold'>How to get rid of fat in stubborn areas without surgery. <br />We use the UltraSlim device which is FDA-cleared for immediate fat reduction.</h2>
        <div className='font20'> 
          Please Fill out the Form below for a free consultation
        </div>
      
       {/* @ts-ignore */}
        <iframe className='yt-video' width="660" height="360" src="https://www.youtube.com/embed/_B-b_066ghQ?start=0&end=185&controls=0&rel=0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>

        <div className='font20'> 
        Request a free consultation below
        </div>

{/* @ts-ignore */}
<iframe className='yt-video' width="660" height="360" src="https://www.youtube.com/embed/TJb7tnkGd88?start=7&end=339&controls=0&rel=0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>

<div className='font20'> 
Request a free consultation below
        </div>
{/* @ts-ignore */}
<iframe className='yt-video' width="660" height="360" src="https://www.youtube.com/embed/3Fq69SrRohg?start=7&end=225&controls=0&rel=0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>
<div className='font20'> 
        Request a free consultation below
        </div>
 {/* @ts-ignore */}
 <iframe className='yt-video' width="660" height="360" src="https://www.youtube.com/embed/Enh4MQK7lZA?start=0&end=24&controls=0&rel=0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>
             
        <div className='font20'> 
        ....
        </div>
            
            {/* @ts-ignore */}
            <iframe src="https://docs.google.com/forms/d/e/1FAIpQLScLGTi0YNAzw10-H06WoAFe25z4DXOiqlkRTSphE98BJ8av0w/viewform?embedded=true" className='googleform' width="640" height="1200" frameBorder="0" marginHeight="0" marginWidth="0">Loading…</iframe>
           
        
                {/* <div className={styles.formContainer}>

                  <h3 className="font20 bold">Enter your info below to request a free consultation</h3>
                            
                        <form onSubmit={handleSubmit(onSubmit)}>

                    <input
                      {...register('name', {required: true, maxLength: 65, minLength: 2,pattern: /[A-Za-z0-9_.-]/})}
                      type="text"
                      placeholder="Enter Your Full Name "
                      className={styles.formInput}
                    />
                    <p className={styles.formError}>
                      {errors.name && <span> Name is required</span>}
                    </p>

                    <input
                      {...register('email', { required: true, maxLength: 65, minLength: 4})}
                      type="email"
                      placeholder="Enter your email address "
                      className={styles.formInput}
                    />
                    <p className={styles.formError}>
                      {errors.email && <span> Email is required</span>}
                    </p>{' '}

                    <input
                      {...register('phone', {pattern: /^\d+$/, required: true})}
                      type="text"
                      placeholder="Enter your cell phone number   "
                      className={styles.formInput}
                    />
                    <p className={styles.formError}>
                      {errors.phone && <span>Your Cell Phone Number is required</span>}
                    </p>
                    
                    <button type="submit" className="cta-btn">
                      Request a Free consultation
                    </button>
                  </form> 
                </div>*/}
                

      </main>

    </>
  )
}

export default Home 
